# Generated by Django 4.1.3 on 2022-11-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Refrigheradora',
            new_name='Refrigeradora',
        ),
    ]
